// ============================================================
// actview — 框架统一入口
//   使用：import { createApp, reactive } from 'actview'
// ============================================================

export {
  createApp,
  defineComponent,
  reactive,
  shallowReactive,
  readonly,
  shallowReadonly,
  markRaw,
  toRaw,
  isReactive,
  isReadonly,
  isProxy,
  isShallow,
  nextTick,
  computed,
  ref,
  shallowRef,
  triggerRef,
  isRef,
  unref,
  unrefs,
  toValue,
  toRef,
  toRefs,
  rawRef,
  watch,
  watchEffect,
  onWatcherCleanup,
  effectScope,
  onScopeDispose,
  onBeforeMount,
  onMounted,
  onUpdated,
  onBeforeUnmount,
  onUnmounted,
  onActivated,
  onDeactivated,
  onErrorCaptured,
  onServerPrefetch,
  onRenderTracked,
  onRenderTriggered,
  provide,
  useInjects,
  useId,
  useRootElement,
  useProp,
  useProps,
  getCurrentInstance,
  createContext,
  renderToString,
  renderToStringAsync,
  hydrate,
  Teleport,
  Transition,
  TransitionGroup,
  KeepAlive,
  ErrorBoundary,
  Suspense,
  lazy,
  getCurrentScope
} from '@actview/core'

export type {
  App,
  SetupContext,
  ComponentOptions,
  Ref,
  ComputedRef,
  WritableComputedRef,
  ComputedOptions,
  WatchSource,
  WatchOptions,
  Context,
  Reactive,
  ShallowReactive,
  ShallowReadonly,
  RefFactory,
  ShallowRefFactory,
  ReactiveFactory,
  ShallowReactiveFactory,
  ReadonlyFactory,
  ShallowReadonlyFactory,
  ComputedFactory,
  ToRefFactory,
  ToRefsFactory,
  WatchFactory,
  WatchEffectFactory
} from '@actview/core'
