// generated by markdownToActView
import { defineComponent } from "@actview/core"
import { createElement } from "@actview/jsx"
import { ref } from '@actview/core'
export const __pageData = JSON.parse("{\"title\":\"Hello ActView\",\"description\":\"\",\"frontmatter\":{},\"headers\":[],\"relativePath\":\"index.md\",\"filePath\":\"index.md\"}")
export default defineComponent(function (props) {
  // ---- <script setup> ----

  const count = ref(0)

  return function () {
    return createElement("div", null, createElement("h1", { "id": "hello-actview", "tabindex": "-1" }, "Hello ActView ", createElement("a", { "class": "header-anchor", "href": "#hello-actview", "aria-label": "Permalink to “Hello ActView”" }, "​")), createElement("p", null, "Intro with ", createElement("strong", null, "bold"), ", ", createElement("code", null, "code"), ", ", createElement("a", { "href": "/a.html" }, "link"), " and & entity."), createElement("blockquote", null, createElement("p", null, "quote line")), createElement("ul", null, createElement("li", null, "item 1"), createElement("li", null, "item 2")), createElement("img", { "src": "/x.png", "alt": "img", "data-x": "1" }), createElement("div", { "class": "raw" }, "raw ", createElement("b", null, "bold"), " <tag>"))
  }
})